// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://lvyngbdxvlarkbzeydzb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imx2eW5nYmR4dmxhcmtiemV5ZHpiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM4NjAyMDYsImV4cCI6MjA2OTQzNjIwNn0.XWhQG7Mmm6Yp6O2tTzaFiLD5oJ3P5qKpLDYubYthY9o";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});